spring:
  application:
    name: livealone
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST}:3306/live_alone
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  data:
    redis:
      host: ${DATABASE_HOST}
      port: 6379
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${DATABASE_HOST}:27017/chatdb?authSource=admin
      port: 27017


  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  jackson:
    property-naming-strategy: SNAKE_CASE
    time-zone: Asia/Seoul

  security:
    oauth2:
      redirect:
        url: ${PROTOCOL}://${FRONT_SERVER_HOST}/oauth2/redirect
      client:
        registration:
          google:
            client-id: ${SOCIAL_GOOGLE_CLIENT_ID}
            client-secret: ${SOCIAL_GOOGLE_CLIENT_SECRET}
            redirect-uri: ${PROTOCOL}://${SERVER_HOST}/login/oauth2/code/google
            scope:
              - profile
              - email
          naver:
            client-id: ${SOCIAL_NAVER_CLIENT_ID}
            client-secret: ${SOCIAL_NAVER_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://${SERVER_HOST}/login/oauth2/code/naver
            scope:
              - email
            client-name: Naver
          kakao:
            client-id: ${SOCIAL_KAKAO_CLIENT_ID}
            client-secret: ${SOCIAL_KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - account_email
              - profile_nickname
            redirect-uri: ${PROTOCOL}://${SERVER_HOST}/login/oauth2/code/kakao
            client-name: Kakao
            provider: kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_HOST}:9092
    consumer:
      bootstrap-servers: ${KAFKA_HOST}:9092

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: ${MAIL_TIMEOUT}
          starttls:
            enable: true

jwt:
  key: ${JWT_SECRET_KEY}
  access-expire-time: ${ACCESS_EXPIRE_TIME}
  refresh-expire-time: ${REFRESH_EXPIRE_TIME}

logging:
  level:
    root: ${LOGGING_LEVEL}

server:
  port: 8080

kakao:
  pay:
    cid: TC0ONETIME
    secret: DEV1983009FCE70023372B535B4EB027DEB9824F
    approval-url: ${PROTOCOL}://${SERVER_HOST}/completePayment
    cancel-url: ${PROTOCOL}://${FRONT_SERVER_HOST}/streaming
    fail-url: ${PROTOCOL}://${FRONT_SERVER_HOST}/streaming

toss:
  api:
    base-url : ${PROTOCOL}://${SERVER_HOST}:7956
    client-key: test_ck_kYG57Eba3GPyQ4zAdxQkVpWDOxmA
    secret-key: test_sk_jExPeJWYVQ1ekabzNRlxV49R5gvN
    ret-url: /completePayment
    ret-cancel-url: /streaming
    result-callback: /completePayment


admin:
  code: ${ADMIN_CODE}
  token: ${ADMIN_TOKEN}
default:
  stream-key: ${DEFAULT_STREAM_KEY}

uri:
  back-server: ${SERVER_HOST}
  front-server: ${FRONT_SERVER_HOST}
  database: ${DATABASE_HOST}
  kafka: ${KAFKA_HOST}

payment:
  kakao:
    cid: ${KAKAO_CID}
    secret-key: ${KAKAO_SECRET_KEY}
    approval-url: ${PROTOCOL}://${SERVER_HOST}/payment/kakao/complete
    cancel-url: ${PROTOCOL}://${SERVER_HOST}/payment
    fail-url: ${PROTOCOL}://${SERVER_HOST}/payment
  toss:
    client-key: ${TOSS_CLIENT_KEY}
    secret-key: ${TOSS_SECRET_KEY}
    ret-url: ${PROTOCOL}://${FRONT_SERVER_HOST}/ORDER-CHECK?orderno=1
    ret-cancel-url: ${PROTOCOL}://${FRONT_SERVER_HOST}/streaming
    result-callback: ${PROTOCOL}://${FRONT_SERVER_HOST}/streaming

